### ISSUE TITLE
[Faeture Reguest]保留hosts中的自定义hostname

### ISSUE THREAD

**Issue by CoelacanthusHex** [levinit/adhosts#3]
如题，我希望能够保留hosts中的自定义hostname
因为火狐和netbeans存在以下bug，如果没写hostname导致启动要 5～10 秒，且改bug至今没有较好的解决方案

https://bugzilla.mozilla.org/show_bug.cgi?id=1296836

谢谢

**Comment by CoelacanthusHex** [comment]
可通过/etc/hostname获取hostname

**Comment by levinit** [comment]
你说的hostname是原来/etc/hosts中信息？
麻烦你把现在的hosts中来自网上的解析内容删掉，只保留你自己原来的hsots内容，新版本更新后，会在新添加hosts信息首尾打上tag，方便更新时去掉。
```shell
#你原来的内容
192.168.0.1  myPC
127.0.0.1  myLapTop
#adhosts_start_tag
#...各种来自网络的hosts解析内容n行
#adhosts_end_tag
```

**Comment by CoelacanthusHex** [comment]
> 你说的hostname是原来/etc/hosts中信息？
> 麻烦你把现在的hosts中来自网上的解析内容删掉，只保留你自己原来的hsots内容，新版本更新后，会在新添加hosts信息首尾打上tag，方便更新时去掉。
> 
> ```shell
> #你原来的内容
> 192.168.0.1  myPC
> 127.0.0.1  myLapTop
> #adhosts_start_tag
> #...各种来自网络的hosts解析内容n行
> #adhosts_end_tag
> ```

谢谢
